Repository LRACT/Miya, pull requests merged in 2020-10, with the labels that each got.

#16 로그 기능 추가하기
  main.py
  modules/devs.py
  modules/events.py
  modules/general.py
  modules/log.py
  modules/mods.py
  modules/register.py
  modules/settings.py
  utils/data.py
Labels: enhancement, must

#17 버그 수정
  main.py
  modules/devs.py
  modules/events.py
  modules/general.py
  modules/log.py
  modules/register.py
  modules/settings.py
  requirements.txt
Labels: bug, emergency, must

#18 Koreanbots 하트 기능 추가
  .github/workflows/flake8.yml
  .github/workflows/pylint.yml
  main.py
  modules/general.py
  utils/koreanbots.py
Labels: enhancement

#19 fix: attribute error
  modules/general.py
Labels: bug

#20 hotfix: response is object
  main.py
Labels: bug
